package com.google.appengine.tools.mapreduce.testmodels;

/**
 * TODO: Insert description here. (generated by kumaranj)
 */
public class ClassWithArray {
  public int id;
  public String name;
  public String[] values;
  /**
   * @param id
   * @param name
   * @param values
   */
  public ClassWithArray(int id, String name, String[] values) {
    this.id = id;
    this.name = name;
    this.values = values;
  }
  
}
