package com.google.appengine.tools.mapreduce.testModels;

/**
 * TODO: Insert description here. (generated by kumaranj)
 */
public class ClassExtendingAbstract extends AbstractClassSample {
  int value;

  /**
   * @param id
   * @param name
   * @param value
   */
  public ClassExtendingAbstract(int id, String name, int value) {
    super(id, name);
    this.value = value;
  }

}
